### ISSUE TITLE
NameError at / uninitialized constant Sinatra::Application::Git

### ISSUE THREAD

**Issue by Manju244** [keithnorm/name-pending-git-log-gui#1]
Hi,

while running at "localhost:4567" giving error as,
NameError at /
uninitialized constant Sinatra::Application::Git 

get '/' do
 error at =>  git = Git.open(SiteConfig.project_dir)  <=
  @log =  git.log.since('1 week ago').path(params[:path] || '')
  haml :root
end
## 

Manjunath

**Comment by keithnorm** [comment]
Hey Manju, yep, my fault there. It requires the git gem so if you just run gem install git it should clear up that error. Thanks for checking it out!

**Comment by Manju244** [comment]
Now its giving error as,
NameError at /
uninitialized constant Sinatra::Application::SiteConfig

i did like this,
SiteConfig = OpenStruct.new(
                 :title => 'Git Show',
                 :author => 'Your Name',
                 :url_base => 'http://localhost:4567/',
                 :project_dir => '/home/manjunath/Desktop/my_app'
               )

## 

Manjunath

**Comment by keithnorm** [comment]
What command are you using to start the app? Should be just ruby application.rb and, though I don't think this should make a difference, I've only ever tested in with ruby 1.9.2.
